### ISSUE TITLE
Need help to setup project with new Handler mapping module

### ISSUE THREAD

**Issue by Matlefebvre1234** [mangas/near-wasm-block#1]
Hi! I try to use the repo to understand how the new handler with mapping for graph node works. i'm not able to build the project. I have every tooling updated (cli, graphnode ....)

when i use 
`npm run build` i got has error :
```Error: Error in subgraph.yaml:

  Path: dataSources > 0 > source > package
  Unexpected key in map: params

  Path: dataSources > 0 > mapping
  Unexpected key in map: file

  Path: dataSources > 0 > mapping
  Unexpected key in map: handler
```
  
  and when i don't use npm  `graph build`
  ```✖ Failed to compile subgraph: Failed to compile data source mapping: Cannot read properties of undefined (reading 'toJS')
Error: Failed to compile data source mapping: Cannot read properties of undefined (reading 'toJS')
    at Compiler._compileDataSourceMapping (/home/mat/eos/graph-tooling/packages/cli/dist/compiler/index.js:315:19)
    at /home/mat/eos/graph-tooling/packages/cli/dist/compiler/index.js:213:167
    at updateInDeeply (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2121:22)
    at updateInDeeply (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2134:23)
    at updateInDeeply (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2134:23)
    at updateIn$1 (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2099:24)
    at Map.updateIn (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2180:12)
    at /home/mat/eos/graph-tooling/packages/cli/dist/compiler/index.js:213:115
    at /home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:3321:30
    at List.withMutations (/home/mat/eos/graph-tooling/node_modules/.pnpm/immutable@4.2.1/node_modules/immutable/dist/immutable.js:2367:5)```

**Comment by mangas** [comment]
Hey @Matlefebvre1234 , I have updated the repo to the new version of the graph cli. Running the following works for me: 

```
pnpm i
pnpm run codegen
pnpm run build
```

Running the protoc step requires an older version of node, the build I ran with node 20
